# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: surprise-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: surprise
  template:
    metadata:
      labels:
        app: surprise
    spec:
      containers:
        - name: surprise-container
          image: laithghnemat/surprise:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: surprise-service
spec:
  selector:
    app: surprise
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
